os: linux
dist: trusty
sudo: required
language: generic
env:
  global:
    - CONDA_ROOT=$HOME/miniconda
addons:
  apt:
    update: true

before_install:
  # install conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $CONDA_ROOT
  - echo ". $CONDA_ROOT/etc/profile.d/conda.sh" >> ~/.bashrc
  - source ~/.bashrc
  # update conda
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install -q conda-build pip

install:
  - conda build -c conda-forge -c defaults conda-recipe

before_script:
  - conda create -n test-env --use-local elf

script:
  - conda activate test-env
  - cd test && python -m unittest discover -v .
