channels:
    - conda-forge
name:
    elf-dev
dependencies:
    - affogato
    - h5py
    - imageio
    - intern
    - mrcfile
    - nifty
    - numba
    - pandas
    - pip
    - scikit-image
    - scikit-learn
    - skan
    - tqdm
    - vigra
    - z5py
