channels:
    - conda-forge
name:
    elf-dev
dependencies:
    - affogato
    - h5py
    - imageio
    # Intern is an optional dependenciy that often crashes the CI.
    # We don't install it by default anymore.
    # - intern
    - mrcfile
    - nifty
    - numba
    - pandas
    - pip
    - scikit-image
    - scikit-learn
    - skan
    - tqdm
    - threadpoolctl
    - vigra
    - z5py
